---
  parser: babel-eslint
  env:
    node: true
  extends: eslint:recommended
  rules:
    array-bracket-spacing:
      - 2
      - never
    block-spacing:
      - 2
      - always
    comma-spacing:
      - 2
      -
        before: false
        after: true
    comma-style:
      - 2
      - last
    computed-property-spacing:
      - 2
      - never
    curly: 2
    eol-last: 2
    indent:
      - 2
      - 2
      -
        SwitchCase: 1
        VariableDeclarator:
          var: 2
          let: 2
          const: 3
    keyword-spacing: space-after-keywords
    linebreak-style: 2
    max-len:
      - 2
      - 100
      - 2
    no-caller: 2
    no-console: 0
    no-debugger: 2
    no-empty: 2
    no-eval: 2
    no-extend-native: 2
    no-extra-bind: 2
    no-invalid-this: 2
    no-irregular-whitespace: 2
    no-iterator: 2
    no-loop-func: 2
    no-mixed-spaces-and-tabs: 2
    no-multi-str: 2
    no-new-func: 2
    no-new-wrappers: 2
    no-proto: 2
    no-script-url: 2
    no-spaced-func: 2
    no-trailing-spaces: 2
    no-unused-expressions: 2
    object-curly-spacing:
      - 2
      - always
    quotes:
      - 2
      - single
      - avoid-escape
    semi:
      - 2
      - always
    space-before-blocks: 2
    space-before-function-paren:
      - 2
      - never
    space-before-keywords: 2
    space-in-parens:
      - 2
      - never
    space-infix-ops: 2
    space-return-throw-case: 2
    space-unary-ops:
      - 2
      -
        words: true
        nonwords: false
    wrap-iife:
      - 2
      - any
